Feature/get primary sensor data
MideTechnology/endaq-python pull request #138
Opened 2022-01-18 18:29 UTC by shanlyMIDE

I need help being able to reference `get_doc` (I thought I did it correctly with `from .files import get_doc` but it doesn't seem to work. In any case this should satisfy https://github.com/MideTechnology/endaq-python/issues/32

Here is a notebook with some test examples (once I can fix the above): https://github.com/MideTechnology/endaq-python/issues/32
![image](https://user-images.githubusercontent.com/35080650/149997048-82bb3327-5bff-4057-89b8-fdb255be5be0.png)

2022-01-20 21:02 UTC, CFlaniganMide commented
The issue is that `.info` is importing `.files`, and `.files` is importing `.info`.  The best way to fix this kind of issue really depends on the situation, but in this case the best course might be to move the `parse_time` function out of `.info` and into `.files`.

2022-01-20 21:25 UTC, StokesMIDE commented
> The issue is that `.info` is importing `.files`, and `.files` is importing `.info`. The best way to fix this kind of issue really depends on the situation, but in this case the best course might be to move the `parse_time` function out of `.info` and into `.files`.

IMHO, the function `parse_time()` should probably be moved to `endaq.ide.util`.

2022-01-20 21:26 UTC, CFlaniganMide commented
> > The issue is that `.info` is importing `.files`, and `.files` is importing `.info`. The best way to fix this kind of issue really depends on the situation, but in this case the best course might be to move the `parse_time` function out of `.info` and into `.files`.
> 
> IMHO, the function `parse_time()` should probably be moved to `endaq.ide.util`.

Yeah, that makes more sense.

2022-01-31 15:55 UTC, StokesMIDE requested changes

2022-01-31 15:55 UTC, StokesMIDE commented on endaq/ide/info.py
> +            print(error_str)
This should be removed, or changed to a warning or logger message

2022-02-01 18:33 UTC, StokesMIDE commented
This should probably get tests before fully approving/merging. Thoughts?

2022-02-03 14:56 UTC, shanlyMIDE commented
I'm going to merge now that @StokesMIDE added the tests and approved it. I'm motivated to get it in because we had some engineers here at Mide looking to see the docs for it because they liked it when I showed it to them in an example script!

2022-02-03 14:56 UTC, merged

2022-02-03 15:02 UTC, shanlyMIDE commented
@StokesMIDE  and @CrepeGoat  do you know when the docs will update? I had been motivated to merge it into dev to show Stan here but I don't see it yet in the docs: https://docs.endaq.com/en/development/endaq/ide.html

I'm not sure if we need to change something in the code to tell the docs to display that function?

2022-02-03 15:09 UTC, CrepeGoat commented
you're looking for this, right? https://docs.endaq.com/en/development/endaq/ide.html#endaq.ide.get_primary_sensor_data

> I had been motivated to merge it into dev to show Stan here
Generally I recommend adding the branch you're working on as a "build source" (not a real term, don't quote me :P) for readthedocs and inspecting the docs changes *before* merging branches. I'll put up a Confluence page on how to do that.

2022-02-03 15:28 UTC, shanlyMIDE commented
well that's the right link URL but the function isn't shown?
![image](https://user-images.githubusercontent.com/35080650/152373551-63c22874-5f3b-40c5-85b1-175c28152d72.png)

2022-02-03 15:35 UTC, CrepeGoat commented
ohhhh that's a weird one. I totally see it on my machine (see below). you may have to reload the page, or clear your cache or something? 🤷‍♂️
![Screen Shot 2022-02-03 at 10 34 11](https://user-images.githubusercontent.com/5862803/152374746-160e9194-d18c-44df-9d97-a5a3f8209457.png)

2022-02-03 16:25 UTC, shanlyMIDE commented
Nice, it's there now! I need to be more patient with `read the docs`! Thanks!