Feature/rolling spectrums
MideTechnology/endaq-python pull request #191
Opened 2022-04-07 21:27 UTC by shanlyMIDE

Lots in this!

- Added `rolling_fft` to `endaq.calc.fft`
- Added `rolling_psd` to `endaq.calc.psd`
- Added `rolling_shock_spectrum` to `endaq.calc.shock`
- Allowed endaq.calc.shock.shock_spectrum to calculate the freqs for you (instead of requiring other function call)
- Added `spectrum_over_time` to `endaq.plot.plots`
- Fixed `octave_spectrogram`

This would close / address: #189, #35, #156,

2022-04-08 14:14 UTC, CFlaniganMide requested changes
Not going to point out all the same stuff as the other PR (yet), just calling out a few things that are unique to this one.

2022-04-08 14:14 UTC, CFlaniganMide commented on endaq/calc/shock.py
> -
This newline is critical to formatting the docs.

2022-04-08 14:14 UTC, CFlaniganMide commented on endaq/plot/plots.py
> +import datetime
Builtin modules should be imported before 3rd party modules.

2022-04-12 20:32 UTC, shanlyMIDE commented
@CFlaniganMide let me know when you want to review this, I have the unit tests in there now and am curious how well written you think they are?

2022-04-26 13:10 UTC, CFlaniganMide commented on tests/calc/test_fft.py
> +        scale = scales.get(normalization, 2. / n)
also this

2022-04-26 13:14 UTC, CFlaniganMide commented on endaq/calc/psd.py
> +    noverlap = nperseg - (nperseg * num_f / num_slices)
use integer division here to ensure data types
```suggestion
    noverlap = nperseg - (nperseg*num_f//num_slices)
```

2022-04-28 20:58 UTC, shanlyMIDE commented
@CFlaniganMide I think I've done everything now correctly, but let me know of course if not!

2022-04-29 14:51 UTC, merged